services:
  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
  
  qdrantDB:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"